import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer, Header, Navigation } from '@components';
import './globals.css';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col h-screen`}>
        <Suspense>
          <Header />
          <Navigation />
        </Suspense>
        <div className="flex flex-1 overflow-x-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
